var json_strikebusiness_2 = {
"type": "FeatureCollection",
"name": "strikebusiness_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Organization": "Santa Fe Community College (AAUP)", "Type": "School" }, "geometry": { "type": "Point", "coordinates": [ -105.997893, 35.605322 ] } },
{ "type": "Feature", "properties": { "Organization": "Institute of American Indian Arts", "Type": "School" }, "geometry": { "type": "Point", "coordinates": [ -106.010088, 35.586905 ] } },
{ "type": "Feature", "properties": { "Organization": "Meow Wolf", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.99652, 35.654695 ] } },
{ "type": "Feature", "properties": { "Organization": "Museum of International Folk Art", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.926582, 35.664165 ] } },
{ "type": "Feature", "properties": { "Organization": "Jambo Cafe", "Type": "Restaurant" }, "geometry": { "type": "Point", "coordinates": [ -105.978011, 35.660481 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Reporter", "Type": "Newspaper" }, "geometry": { "type": "Point", "coordinates": [ -105.935427, 35.688378 ] } },
{ "type": "Feature", "properties": { "Organization": "Trader Joe's", "Type": "Grocery store" }, "geometry": { "type": "Point", "coordinates": [ -105.953372, 35.673011 ] } },
{ "type": "Feature", "properties": { "Organization": "Whole Foods", "Type": "Grocery store" }, "geometry": { "type": "Point", "coordinates": [ -105.950046, 35.679116 ] } },
{ "type": "Feature", "properties": { "Organization": "Natural Grocers", "Type": "Grocery store" }, "geometry": { "type": "Point", "coordinates": [ -105.954279, 35.674875 ] } },
{ "type": "Feature", "properties": { "Organization": "Albertsons", "Type": "Grocery store" }, "geometry": { "type": "Point", "coordinates": [ -105.955444, 35.645719 ] } },
{ "type": "Feature", "properties": { "Organization": "Museum of Indian Arts & Culture", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.925656, 35.664478 ] } },
{ "type": "Feature", "properties": { "Organization": "Felipe's Tacos", "Type": "Restaurant" }, "geometry": { "type": "Point", "coordinates": [ -105.972307, 35.65831 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Indian School", "Type": "School" }, "geometry": { "type": "Point", "coordinates": [ -105.967694, 35.671069 ] } },
{ "type": "Feature", "properties": { "Organization": "Pantry Restaurant", "Type": "Restaurant" }, "geometry": { "type": "Point", "coordinates": [ -105.972428, 35.664901 ] } },
{ "type": "Feature", "properties": { "Organization": "IAIA Museum of Contemporary Native Art", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.937014, 35.687085 ] } },
{ "type": "Feature", "properties": { "Organization": "Tune Up Cafe", "Type": "Restaurant" }, "geometry": { "type": "Point", "coordinates": [ -105.958657, 35.681338 ] } },
{ "type": "Feature", "properties": { "Organization": "Counter Culture Coffee", "Type": "Coffee Shop" }, "geometry": { "type": "Point", "coordinates": [ -105.962886, 35.672717 ] } },
{ "type": "Feature", "properties": { "Organization": "Travel Bug", "Type": "Bookstore \/ coffee" }, "geometry": { "type": "Point", "coordinates": [ -105.933785, 35.685471 ] } },
{ "type": "Feature", "properties": { "Organization": "Collected Works", "Type": "Bookstore \/ coffee" }, "geometry": { "type": "Point", "coordinates": [ -105.941045, 35.686694 ] } },
{ "type": "Feature", "properties": { "Organization": "Big Star Books and Music", "Type": "Bookstore" }, "geometry": { "type": "Point", "coordinates": [ -105.945664, 35.684358 ] } },
{ "type": "Feature", "properties": { "Organization": "Iconik Coffee", "Type": "Coffee Shop" }, "geometry": { "type": "Point", "coordinates": [ -105.964254, 35.665156 ] } },
{ "type": "Feature", "properties": { "Organization": "Ecco Espresso", "Type": "Coffee Shop" }, "geometry": { "type": "Point", "coordinates": [ -105.935832, 35.688575 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Community Foundation", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.935676, 35.680809 ] } },
{ "type": "Feature", "properties": { "Organization": "Nature Conservancy ", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.934597, 35.688149 ] } },
{ "type": "Feature", "properties": { "Organization": "Trust for Public Land", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.94616, 35.681064 ] } },
{ "type": "Feature", "properties": { "Organization": "Sweetwater Harvest", "Type": "Restaurant" }, "geometry": { "type": "Point", "coordinates": [ -105.959916, 35.666563 ] } },
{ "type": "Feature", "properties": { "Organization": "Georgia O'Keeffe Museum ", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.941314, 35.689196 ] } },
{ "type": "Feature", "properties": { "Organization": "SITE", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.9496, 35.681577 ] } },
{ "type": "Feature", "properties": { "Organization": "Smith's", "Type": "Grocery store" }, "geometry": { "type": "Point", "coordinates": [ -105.979866, 35.659549 ] } },
{ "type": "Feature", "properties": { "Organization": "Second Street Brewery", "Type": "Bar" }, "geometry": { "type": "Point", "coordinates": [ -105.948735, 35.682588 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Brewing Co. ", "Type": "Bar" }, "geometry": { "type": "Point", "coordinates": [ -106.051563, 35.596613 ] } },
{ "type": "Feature", "properties": { "Organization": "Books of Interest", "Type": "Bookstore" }, "geometry": { "type": "Point", "coordinates": [ -105.963311, 35.671897 ] } },
{ "type": "Feature", "properties": { "Organization": "Goodwill", "Type": "Thrift store" }, "geometry": { "type": "Point", "coordinates": [ -105.993871, 35.653483 ] } },
{ "type": "Feature", "properties": { "Organization": "Ace Hardware", "Type": "Commercial Store" }, "geometry": { "type": "Point", "coordinates": [ -105.9771, 35.660939 ] } },
{ "type": "Feature", "properties": { "Organization": "35� North", "Type": "Coffee Shop" }, "geometry": { "type": "Point", "coordinates": [ -105.939133, 35.686824 ] } },
{ "type": "Feature", "properties": { "Organization": "St. Johns College", "Type": "School" }, "geometry": { "type": "Point", "coordinates": [ -105.91229, 35.666732 ] } },
{ "type": "Feature", "properties": { "Organization": "REI", "Type": "Commercial Store" }, "geometry": { "type": "Point", "coordinates": [ -105.948221, 35.683963 ] } },
{ "type": "Feature", "properties": { "Organization": "Center for Contemporary Arts", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.938179, 35.673697 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Children's Museum", "Type": "Museum " }, "geometry": { "type": "Point", "coordinates": [ -105.936906, 35.673045 ] } },
{ "type": "Feature", "properties": { "Organization": "Betterday Coffee", "Type": "Coffee Shop" }, "geometry": { "type": "Point", "coordinates": [ -105.958209, 35.689488 ] } },
{ "type": "Feature", "properties": { "Organization": "op.cit.books", "Type": "Bookstore" }, "geometry": { "type": "Point", "coordinates": [ -105.951041, 35.692426 ] } },
{ "type": "Feature", "properties": { "Organization": "Big Adventure Comics", "Type": "Bookstore" }, "geometry": { "type": "Point", "coordinates": [ -105.946761, 35.684874 ] } },
{ "type": "Feature", "properties": { "Organization": "New Mexico Wilderness Alliance", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.932248, 35.684804 ] } },
{ "type": "Feature", "properties": { "Organization": "The Housing Trust", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.96128, 35.682604 ] } },
{ "type": "Feature", "properties": { "Organization": "New Mexico Coalition Against Domestic Violence", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.950255, 35.67186 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Council on International Relations", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.939319, 35.692595 ] } },
{ "type": "Feature", "properties": { "Organization": "Waterlines", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.936573, 35.687423 ] } },
{ "type": "Feature", "properties": { "Organization": "Warehouse 21", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.950583, 35.681419 ] } },
{ "type": "Feature", "properties": { "Organization": "SER - Jobs for Progress", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.98269, 35.659665 ] } },
{ "type": "Feature", "properties": { "Organization": "Garcia St. Books", "Type": "Bookstore" }, "geometry": { "type": "Point", "coordinates": [ -105.933447, 35.680498 ] } },
{ "type": "Feature", "properties": { "Organization": "Kaune's Neighborhood Market", "Type": "Grocery store" }, "geometry": { "type": "Point", "coordinates": [ -105.937668, 35.680932 ] } },
{ "type": "Feature", "properties": { "Organization": "Architecture2030", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.946171, 35.681073 ] } },
{ "type": "Feature", "properties": { "Organization": "Rio Chama Steakhouse", "Type": "Restaurant" }, "geometry": { "type": "Point", "coordinates": [ -105.938445, 35.683234 ] } },
{ "type": "Feature", "properties": { "Organization": "Audubon New Mexico", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.888526, 35.690063 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Human Rights Alliance", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.935736, 35.687603 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Art Institute ", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.980871, 35.65776 ] } },
{ "type": "Feature", "properties": { "Organization": "Pecos Trail Cafe", "Type": "Coffee Shop" }, "geometry": { "type": "Point", "coordinates": [ -105.933269, 35.64785 ] } },
{ "type": "Feature", "properties": { "Organization": "Quivira Coalition", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.968302, 35.665961 ] } },
{ "type": "Feature", "properties": { "Organization": "United Way of Santa Fe", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -106.004971, 35.66016 ] } },
{ "type": "Feature", "properties": { "Organization": "Santa Fe Media Network", "Type": "Commercial Store" }, "geometry": { "type": "Point", "coordinates": [ -105.947913, 35.676729 ] } },
{ "type": "Feature", "properties": { "Organization": "Broken Spoke", "Type": "Commercial Store" }, "geometry": { "type": "Point", "coordinates": [ -105.965791, 35.669566 ] } },
{ "type": "Feature", "properties": { "Organization": "Bike n Sport", "Type": "Commercial Store" }, "geometry": { "type": "Point", "coordinates": [ -105.950669, 35.672546 ] } },
{ "type": "Feature", "properties": { "Organization": "Think New Mexico", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.939248, 35.681373 ] } },
{ "type": "Feature", "properties": { "Organization": "Drug Policy Alliance - New Mexico", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.932096, 35.684773 ] } },
{ "type": "Feature", "properties": { "Organization": "Farm to Table", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.938067, 35.681029 ] } },
{ "type": "Feature", "properties": { "Organization": "Upaya Zen Center", "Type": "Religious" }, "geometry": { "type": "Point", "coordinates": [ -105.9077, 35.682442 ] } },
{ "type": "Feature", "properties": { "Organization": "McCune Foundation", "Type": "Nonprofit" }, "geometry": { "type": "Point", "coordinates": [ -105.932212, 35.684993 ] } },
{ "type": "Feature", "properties": { "Organization": "Caffee Greco", "Type": "Coffee Shop" }, "geometry": { "type": "Point", "coordinates": [ -105.93323, 35.683128 ] } }
]
}
